<?php

$additionalHeaders = '';
require_once('./page_header.php');
require_once('./page_nav.php');
?>
<main>
    <div class="titlebar">
        <h1>The Desert Willow Ranch B&B</h1>
        <h2>History</h2>
    </div>

    <article>
        <img src="images/20161024_190620_IMG_8816.JPG" style="width: 300px; float: left; margin: 0 2rem 2rem 0;" />
        <p>Desert Willow Ranch – what’s in a name? The correlation began in the 1950s when Zip and Jinny Peterson were newly married and moved to Tucson from back east. Zip came from Massachusetts and Jinny came from Connecticut.</p>
        <p>Zip and Jinny shared a deep passion for horses. Zip rode horses as a boy and played ice hockey and baseball. He was so good he was offered two full scholarships to universities in Massachusetts, one for his prowess as a goalie and the other as a catcher. Jinny came from a prominent family who owned the Worden Dairy in Waterbury, Connecticut. Her college training was as a bookkeeper so she was well equipped to work in the family business. They both met at a rodeo event in upstate New York. The two quickly knew they were destined to be together when Zip asked Jinny to accompany him on a trip out west to Arizona, a state still wild and rich in cowboy culture. Jinny’s reply was quite simple, “not unless we’re married” and the rest is history! They were married in Dec 1950 and immediately found their way to the Tanque Verde area.</p>
        <p>Back then, Tanque Verde was a very rural community entirely separate from Tucson and surrounded by dude ranches, popular vacation spots. These ranches provided a western cowboy cultural experience for those who had the means. “Dudes” was the term used for those venturing out west to try their hand at riding and experience ranching. Very popular in the ‘50s, one Dude Ranch in particular, captured the hearts of Zip & Jinny. If you were to look through Jinny’s scrapbooks of those years, you would quickly realize that this was the ranch they enjoyed working at the most. Desert Willow Ranch held a special place in their hearts and lives! So much so, Jinny planted a “Desert Willow” tree (her favorite) in the front yard soon after their purchase of the future ranch.</p>

        <img src="images/FB_IMG_1683000449317.jpg" style="width: 300px; float: right; margin: 0 0 2rem 2rem;" />
        <p>Fast forward to the early 60s and you’ll learn that the couple grew in their marriage from their work at Desert Willow and their constant traveling as Rodeo contestants throughout the U.S. From small town rodeos to the grand stage at Madison Square Garden (predecessor to the National Finals now held in Las Vegas), they honed their skills. Zip excelled as a professional Saddle Bronc Rider, Steer Wrestler, and Calf Roper and Jinny in Barrel Racing. They would rodeo in the Spring and Fall, work at boy’s and girl’s camp in the summers (affiliated with Desert Willow but in Wisconsin), and then return to Tanque Verde to work the Dude Ranch in the winters.</p>
        <p>But things were about to change and in 1963 their first son was born. They set their sights on a 3-acre piece of property in a sparsely inhabited area of Tanque Verde that is now 381 S. Pinto Place. It started out as a very simple two bedroom, one bath, cinder block home in possibly the late 40s or very early 50s, and had grown to three bedrooms, 2 baths by 1953. The property was surrounded by nothing but desert and spectacular views of the Catalina and Rincon Mountain ranges. Zip and Jinny set to work on the property, first building a small barn, known as “The Shop”, with an integrated tack room (now serving as the B&B office). Next, they added an arena, complete with calf chutes and lights and horse pens. Friday night roping events quickly became a popular attraction for area cowboys and friends. Here Zip honed his talents as a farrier (horse shoer) by day, and Jinny was busy raising their son, Troy. Zip quickly became a highly sought-after farrier due to his training in coal forge work, his charismatic personality, and deep understanding of horses.</p>
        <p>By the mid-60s they were well established at the ranch when their second son, Lee, came along. As the years crept by the horseshoeing slowly took its toll on Zip’s body, and horse breeding become a more important part of the ranch. Jinny’s incredible love for teaching kids about horses led her to lead the largest 4H horse club in Arizona for many years and the ranch was an integral part of that adventure. Then began to learn about horse racing. He quickly became successful locally and then branched out in that industry to state meets and from state to state. They bought adjoining acreage and created a training track (still visible in aerial photos of the area) and horse pastures. The 3-acre ranch turned into 16-acres and by the earch 70's a large racehorse training operation emerged. In the 1980's and 90's, Zip was recognized as a successful racehorse trainer and even qualified for the most prestigious Quarter Horse Racing event in the world, the All-American Futurity in Ruidoso, NM.</p>
        <p>The years rolled along and the boys grew and became men, marrying, and moving away. Zip and Jinny worked to continue in their love and passion for raising and now racing horses. Zip traveled extensively to racetracks around the country during those years. Lee became the son who would catch the bug for horse racing and eventually become a racing official in Arizona and a sought-after starter for almost every racetrack in the state. Troy honorably served in the U.S. Army and experienced his first real-world deployment to the Persian Gulf and also the horrors of combat in Mogadishu, Somalia (which became known as Blackhawk Down).</p>
        <p>Eventually, age caught up with Zip and Jinny and the large operation dwindled to a handful of horses. They began to struggle financially and were forced to sell large portions of the 16 acres. Jinny worked for decades in a local insurance office as gray hair and health concerns emerged for both. Troy moved back home, retiring from active duty, and was needed to help care for both as the years of hard labor and financial ups and downs took their toll. Jinny lost her battle to illness in 2011 and Zip suffered greatly in losing his wife of nearly 62-years. He succumbed to a variety of health issues requiring much care and passed away in 2017. With the property under a reverse mortgage and HUD moving in to claim the final 3.3 acres, Troy and his wife, Karen, faced the impossible task of saving the ranch from an imminent foreclosure. Through prayer and faith, a miracle occurred, HUD’s second appraisal in two years came back at an extremely low estimate of value and allowed Troy and Karen to buy it back from the government at EXACTLY the amount they had saved.</p>
        <p>A new labor of love has emerged and since 2018. Troy and Karen have worked tirelessly to bring the ranch back from ruin to what it has become today. In honor of Zip and Jinny’s hard work and dedication, “Desert Willow Ranch”, where their arduous life’s journey began in earnest, is being reborn. In this project Troy has sought to give something back to Karen for all her years of sacrifice and service to our nation in the hardest of all military duties, being a spouse to a career Army combat veteran. All those years it has been her dream to operate and be the hostess of a bed and breakfast. Through the blood, sweat (LOTS of sweat!) and tears, God has blessed, and now it is time to share this beautiful place and its legacy with others.</p>
        <strong>Welcome to the Desert Willow Ranch B&B! We hope your stay is as wonderful and memorable as the legacy of this ranch.</strong>
</article>
